apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/subham601/argo-demo.git
    path: manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
